apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  labels:
    service: kafka-exporter-service
spec:
  type: ClusterIP
  ports:
    - port: 9308
      name: kafka-exporter-port
      targetPort: 9308
      protocol: TCP
  selector:
    service: kafka-exporter
status:
  loadBalancer: {}