apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-storage-pvc
  namespace: monitoring
  labels:
    vol: prom-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
