apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-storage-pv
  namespace: monitoring
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: cassandra-disk
    fsType: ext4
