apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv
spec:
  storageClassName: "cassandra-sc"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: database
    name: cassandra-pvc
  gcePersistentDisk:
    pdName: cassandra-disk
    fsType: ext4
