{
 "title": "Kafka & Spark Metrics",
 "tags": [
  "Kafka",
  "Spark"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Kafka job",
    "query": "label_values(kafka_consumergroup_current_offset, job)"
   },
   {
    "name": "instance",
    "label": "Kafka instance",
    "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Kafka topic",
    "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
   },
   { "name": "executor_id", "label": "Spark executor ID", "query": { "query": "label_values(executor_id)" } }
  ]
 },
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Non-consumed messages count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{partition=~'0', instance=~'$instance', topic=~\"$topic\"} - on() kafka_consumergroup_current_offset{instance=~'$instance',topic=~\"$topic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{instance=\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages produced per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{instance=~'$instance', topic=~\"$topic\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages consumed per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{instance=~'$instance',topic=~\"$topic\"}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{instance=\"$instance\",topic=~\"$topic\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  { "title": "Spark", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Percentage of memory used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_executor_memoryUsed_bytes{executor_id=\"$executor_id\"} / metrics_executor_maxMemory_bytes{executor_id=\"$executor_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks completed per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 31 },
   "targets": [
    {
     "expr": "(increase(metrics_executor_completedTasks_total{executor_id=\"$executor_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of failed task per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(increase(metrics_executor_failedTasks_total{executor_id=\"$executor_id\"}[1m])) /\n(increase(metrics_executor_totalTasks_total{executor_id=\"$executor_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}