apiVersion: apps/v1 
kind: Deployment 
metadata: 
   name: consumer-depl
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: consumer-depl
  template: 
    metadata: 
      labels: 
        app: consumer-depl  
    spec: 
      containers: 
        - name: consumer
          image: registry.gitlab.com/viviane.qian/projet-sdtd/consumer
          ports: 
            - containerPort: 9092
          envFrom:
          - configMapRef:
              name: consumer-configmap
      imagePullSecrets:
        - name: registry-credentials