apiVersion: v1
kind: Pod
metadata:
  name: kowl-pod
  namespace: messaging
  labels:
    app: kowl
spec:
  containers:
  - name: kowl-container
    image: quay.io/cloudhut/kowl:master
    ports:
    - containerPort: 8080
    env:
    - name: KAFKA_BROKERS
      value: my-cluster-kafka-bootstrap:9092
  dnsPolicy: ClusterFirst