apiVersion: v1
kind: Service
metadata:
  name: kowl-service
  namespace: messaging
spec:
  selector:
    app: kowl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
