{
 "title": "Spark Metrics",
 "time": { "from": "2023-12-21T09:23:49.280Z", "to": "2023-12-21T09:58:45.929Z" },
 "templating": {
  "list": [
   { "name": "executor_id", "label": "Executor", "query": { "query": "label_values(executor_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Tasks completed per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(increase(metrics_executor_completedTasks_total{executor_id=\"$executor_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of failed task per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(increase(metrics_executor_failedTasks_total{executor_id=\"$executor_id\"}[1m])) /\n(increase(metrics_executor_totalTasks_total{executor_id=\"$executor_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of memory used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_executor_memoryUsed_bytes{executor_id=\"$executor_id\"} / metrics_executor_maxMemory_bytes{executor_id=\"$executor_id\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}