apiVersion: apps/v1 
kind: Deployment 
metadata: 
   name: webserver-depl
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: webserver-depl
  template: 
    metadata: 
      labels: 
        app: webserver-depl
    spec: 
      containers: 
        - name: webserver
          image: registry.gitlab.com/viviane.qian/projet-sdtd/webserver
          ports: 
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: webserver-configmap
      imagePullSecrets:
        - name: registry-credentials
