apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-load-keyspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-load-keyspace
  template:
    metadata:
      labels: 
        app: cassandra-load-keyspace
    spec:
      containers:
      - name: cassandra-load-keyspace
        image: cassandra:5.0
        command:
        - "/bin/bash"
        - "-c"
        - "echo loading cassandra keyspace && ls /data && cqlsh -f /data/cassandra_schema.cql"
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: "SDTD Cluster"
        - name: CASSANDRA_SERVICE_HOST
          value: cassandra
        - name: CASSANDRA_SERVICE_PORT
          value: "9042"
        volumeMounts:
        - mountPath: /data
          name: volume
      volumes:
      - name: volume
        hostPath:
          path: /data
