apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: database
spec:
  selector:
    matchLabels:
      app: cassandra
  serviceName: cassandra-service
  replicas: 3
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - env:
            - name: CASSANDRA_CLUSTER_NAME
              value: SDTD Cluster
            - name: CASSANDRA_SEEDS
              value: cassandra-0.cassandra-service.database.svc.cluster.local
            - name: MAX_HEAP_SIZE
              value: 256M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          image: cassandra:5.0
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  if cqlsh -v ; then
                    cqlsh -f /etc/cassandra_script/cassandra_schema.cql
                    exit 0
                  else
                    exit 1
                  fi
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 10
          name: cassandra
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          volumeMounts:
            - mountPath: /var/lib/cassandra/data
              name: cassandra-data
            - mountPath: /etc/cassandra_script
              name: cassandra-script-volume
      restartPolicy: Always
      volumes:
      - name: cassandra-script-volume
        configMap:
          name: cassandra-script
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
status: {}
