kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      routes:
        - receiver: discord
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: velocite.sdtd@gmail.com
        send_resolved: true
        require_tls: false
    - name: discord
      discord_configs:
      - webhook_url: https://discord.com/api/webhooks/1176457042173632522/Glxsj9SYH_ajMD9WfmqaK6VKYSV7wWcsr9W7Rlv3N5U4WxSnx1aMRX5T3vC8IZzeQmzH


